name: Publish GH Pages
on:
  release:
    types: [created]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git remote -v
          npm install
          npm run deploy -- -u "David Callizaya <davidcallizaya@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
